#!/bin/bash

<<*

┌─┐┌┬┐┌─┐┌┬┐┬ ┬┌─┐┌┐ ┌─┐┬─┐
└─┐ │ ├─┤ │ │ │└─┐├┴┐├─┤├┬┘
└─┘ ┴ ┴ ┴ ┴ └─┘└─┘└─┘┴ ┴┴└─

─┐ ┌─┐┌┬┐┌┬┐┌─┐┬─┐┬ ┬
├┴┐├─┤ │  │ ├┤ ├┬┘└┬┘
──┘┴ ┴ ┴  ┴ └─┘┴└─ ┴

─ ryuJin25

*
case $BUTTON in
	1) $HOME/.local/bin/rofiscripts/pop-battery;; 
esac

