#!/bin/sh

<<*

┌─┐┌┬┐┌─┐┌┬┐┬ ┬┌─┐┌┐ ┌─┐┬─┐
└─┐ │ ├─┤ │ │ │└─┐├┴┐├─┤├┬┘
└─┘ ┴ ┴ ┴ ┴ └─┘└─┘└─┘┴ ┴┴└─

──┐┌─┐┬ ┬┌─┐┬─┐
├─┘│ ││││├┤ ├┬┘
┴  └─┘└┴┘└─┘┴└─

─ ryuJin25

*

case $BUTTON in
	1) ~/.local/bin/rofiscripts/powermenu ;;
	3) ~/.local/bin/lock ;;
esac

