#!/bin/bash

<<*

┌─┐┌┬┐┌─┐┌┬┐┬ ┬┌─┐┌┐ ┌─┐┬─┐
└─┐ │ ├─┤ │ │ │└─┐├┴┐├─┤├┬┘
└─┘ ┴ ┴ ┴ ┴ └─┘└─┘└─┘┴ ┴┴└─

┬ ┬┬┌─┐┬  
││││├┤ │  
─┴┘┴└  ┴ 

─ ryuJin25

*

case $BUTTON in
	1) ~/.local/bin/rofiscripts/wifimenu ;;
	3) kcmshell5 kcm_networkmanagement 
#  SPEED=$(awk 'NR==3 {print $3 "00%"}''' /proc/net/wireless)
#  dunstify "Network Speed" "$SPEED"
  ;;
esac
